name: 'AWS Credentials Test'

on:
  push:
    branches: [ "develop" ]

jobs:
  test-aws-credentials:
    name: 'Test AWS Credentials'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Test AWS Connection
        run: |
          echo "=== Testing AWS Connection ==="
          aws sts get-caller-identity
          echo "AWS credentials are working!"

      - name: Test AWS S3 Access
        run: |
          echo "=== Testing AWS S3 Access ==="
          aws s3 ls
          echo "S3 access is working!"
