name: 'Debug Workflow'

on:
  push:
    branches: [ "develop" ]

jobs:
  # Test 1: Just Terraform
  test-terraform:
    name: 'Test Terraform Only'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.5.0'

      - name: Test Terraform
        run: |
          echo "=== Testing Terraform Only ==="
          terraform version

  # Test 2: Just Terragrunt
  test-terragrunt:
    name: 'Test Terragrunt Only'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terragrunt
        uses: gruntwork-io/setup-terragrunt@v0.0.3
        with:
          terragrunt-version: '0.50.0'

      - name: Test Terragrunt
        run: |
          echo "=== Testing Terragrunt Only ==="
          terragrunt --version

  # Test 3: Both Together
  test-both:
    name: 'Test Both Together'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.5.0'

      - name: Setup Terragrunt
        uses: gruntwork-io/setup-terragrunt@v0.0.3
        with:
          terragrunt-version: '0.50.0'

      - name: Test Both
        run: |
          echo "=== Testing Both Together ==="
          terraform version
          terragrunt --version
