name: 'Terraform CI/CD Pipeline'

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - 'environments/**'
      - 'modules/**'
      - '.github/workflows/terraform.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'environments/**'
      - 'modules/**'
      - '.github/workflows/terraform.yml'

env:
  TF_VERSION: '1.5.0'
  TERRAGRUNT_VERSION: '0.50.0'
  AWS_REGION: 'us-east-1'
  TERRAGRUNT_DOWNLOAD: '.tg-cache'

jobs:
  # Job 1: Terraform Format Check
  format:
    name: 'Terraform Format Check'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format Check
        run: |
          echo "=== Terraform Format Check ==="
          echo "Current directory: $(pwd)"
          echo "Looking for .tf files:"
          find . -name "*.tf" -not -path "./.git/*" || echo "No .tf files found"
          if find . -name "*.tf" -not -path "./.git/*" -print -quit | grep -q .; then
            echo "Running terraform fmt -check -diff..."
            find . -name "*.tf" -not -path "./.git/*" -exec terraform fmt -check -diff {} \;
          else
            echo "No Terraform files found to check"
          fi

  # Job 2: Terraform Validate
  validate:
    name: 'Terraform Validate'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, staging, prod]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Setup Terragrunt (Working Action)
        uses: autero1/action-terragrunt@v1.2.0
        with:
          terragrunt_version: ${{ env.TERRAGRUNT_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: |
          echo "=== Initializing Terragrunt for ${{ matrix.environment }} ==="
          cd environments/${{ matrix.environment }}/us-east-1/vpc
          terragrunt init --terragrunt-non-interactive

      - name: Terraform Validate
        run: |
          echo "=== Validating Terraform for ${{ matrix.environment }} ==="
          cd environments/${{ matrix.environment }}/us-east-1/vpc
          terragrunt validate

  # Job 3: Security Scan
  security:
    name: 'Security Scan'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Run TFSec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: environments/

  # Job 4: Plan Infrastructure
  plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    needs: [format, validate, security]
    strategy:
      matrix:
        environment: [dev, staging, prod]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Setup Terragrunt (Working Action)
        uses: autero1/action-terragrunt@v1.2.0
        with:
          terragrunt-version: ${{ env.TERRAGRUNT_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Plan
        run: |
          echo "=== Planning Infrastructure for ${{ matrix.environment }} ==="
          cd environments/${{ matrix.environment }}/us-east-1/vpc
          terragrunt plan -out=tfplan

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-${{ matrix.environment }}
          path: environments/${{ matrix.environment }}/us-east-1/vpc/tfplan

  # Job 5: Deploy Infrastructure (only on main branch)
  deploy:
    name: 'Deploy Infrastructure'
    runs-on: ubuntu-latest
    needs: [plan]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    strategy:
      matrix:
        environment: [dev, staging, prod]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Setup Terragrunt (Working Action)
        uses: autero1/action-terragrunt@v1.2.0
        with:
          terragrunt-version: ${{ env.TERRAGRUNT_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan-${{ matrix.environment }}

      - name: Terraform Apply
        run: |
          echo "=== Deploying Infrastructure for ${{ matrix.environment }} ==="
          cd environments/${{ matrix.environment }}/us-east-1/vpc
          terragrunt apply -auto-approve

  # Job 6: Cleanup (only on main branch)
  cleanup:
    name: 'Cleanup Old Artifacts'
    runs-on: ubuntu-latest
    needs: [deploy]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Delete Artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: terraform-plan-*