name: 'Test Workflow'

on:
  push:
    branches: [ "develop" ]

jobs:
  test:
    name: 'Test Job'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Step
        run: |
          echo "Hello World!"
          echo "Current directory: $(pwd)"
          echo "Files in current directory:"
          ls -la
